spring.main.show_banner=false
endpoints.shutdown.enabled=true

server.port=8002

source.sis.datasource.url=jdbc:postgresql://127.0.0.1:5436/db_prima
source.sis.datasource.username=adempiere
source.sis.datasource.password=adempiere
source.sis.datasource.max-pool-size=100
source.sis.datasource.min-idle=2
target.sis.datasource.connection-timeout=30000
source.sis.datasource.idle-timeout=600000
source.sis.datasource.max-lifetime=1800000

# ================= TARGET DATABASE =================
target.sis.datasource.url=jdbc:postgresql://127.0.0.1:5436/db_prima2
target.sis.datasource.username=adempiere
target.sis.datasource.password=adempiere
target.sis.datasource.max-pool-size=100
target.sis.datasource.min-idle=2
target.sis.datasource.connection-timeout=30000
target.sis.datasource.idle-timeout=600000
target.sis.datasource.max-lifetime=1800000


#server.port=8011
#source.sis.datasource.maxpool=100
#source.sis.datasource.url=jdbc:postgresql://localhost:5001/db_erp_sci
#source.sis.datasource.port=5001
#source.sis.datasource.username=adempiere
#source.sis.datasource.password=s1st3m4t1k4@J4ya



sis.id.dir_po=/home/budiest93/Documents/CEPERAN/psi/prima/task/import/PO/
sis.id.ad_client_id=11
sis.id.ad_user_id=101
sis.id.c_currency_id=303
sis.id.po_doctype_id=126
sis.id.po_pricelist_id=102
sis.id.po_paymentterm_id=105