spring.main.show_banner=false
endpoints.shutdown.enabled=true

server.port=8002

source.sis.datasource.maxpool=500
source.sis.datasource.url=jdbc:postgresql://localhost:5436/db_prima
source.sis.datasource.port=5436
source.sis.datasource.username=adempiere
source.sis.datasource.password=adempiere

target.sis.datasource.maxpool=500
target.sis.datasource.url=jdbc:postgresql://localhost:5436/db_prima2
target.sis.datasource.port=5436
target.sis.datasource.username=adempiere
target.sis.datasource.password=adempiere

#server.port=8011
#source.sis.datasource.maxpool=500
#source.sis.datasource.url=jdbc:postgresql://localhost:5001/db_erp_sci
#source.sis.datasource.port=5001
#source.sis.datasource.username=adempiere
#source.sis.datasource.password=s1st3m4t1k4@J4ya



sis.id.dir_po=/home/budiest93/Documents/CEPERAN/psi/prima/task/import/PO/
sis.id.ad_client_id=11
sis.id.ad_user_id=101
sis.id.c_currency_id=303
sis.id.po_doctype_id=126
sis.id.po_pricelist_id=102
sis.id.po_paymentterm_id=105